<?xml version='1.1' encoding='UTF-8'?>
<build>
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <com.cloudbees.jenkins.GitHubPushCause plugin="github@1.40.0">
            <pushedBy>Mark-Pino</pushedBy>
          </com.cloudbees.jenkins.GitHubPushCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <hudson.triggers.SCMTrigger_-BuildAction/>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.21-451.vd51df8df52ec">
      <queuingDurationMillis>6348</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>0</buildableDurationMillis>
      <waitingDurationMillis>6346</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
    <com.cloudbees.plugins.credentials.builds.CredentialsParameterBinder plugin="credentials@1378.v81ef4269d764">
      <boundCredentials class="concurrent-hash-map"/>
    </com.cloudbees.plugins.credentials.builds.CredentialsParameterBinder>
    <hudson.plugins.git.util.BuildData plugin="git@5.5.0">
      <buildsByBranchName>
        <entry>
          <string>refs/remotes/origin/main</string>
          <hudson.plugins.git.util.Build>
            <marked plugin="git-client@5.0.0">
              <sha1>e565ae92f22a143b559c85313815b9bef44fcd8c</sha1>
              <branches class="list">
                <hudson.plugins.git.Branch>
                  <sha1 reference="../../../sha1"/>
                  <name>refs/remotes/origin/main</name>
                </hudson.plugins.git.Branch>
              </branches>
            </marked>
            <revision reference="../marked"/>
            <hudsonBuildNumber>7</hudsonBuildNumber>
          </hudson.plugins.git.util.Build>
        </entry>
      </buildsByBranchName>
      <lastBuild reference="../buildsByBranchName/entry/hudson.plugins.git.util.Build"/>
      <remoteUrls>
        <string>https://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@github.com/Mark-Pino/SistemaVentasLaravel.git</string>
      </remoteUrls>
    </hudson.plugins.git.util.BuildData>
    <hudson.scm.SCMRevisionState_-None/>
    <hudson.plugins.sonar.action.SonarAnalysisAction plugin="sonar@2.17.2">
      <installationName>sonarqube</installationName>
      <installationUrl>http://docker.sonar:9000/</installationUrl>
      <credentialsId>Sonarqube</credentialsId>
      <ceTaskId>AZK7FpQ1XINOz-rqM9Nh</ceTaskId>
      <url>http://docker.sonar:9000/dashboard?id=sistema_ventas_laravel</url>
      <serverUrl>http://docker.sonar:9000</serverUrl>
      <isNew>true</isNew>
      <isSkipped>false</isSkipped>
    </hudson.plugins.sonar.action.SonarAnalysisAction>
  </actions>
  <queueId>47</queueId>
  <timestamp>1729714782347</timestamp>
  <startTime>1729714782420</startTime>
  <result>SUCCESS</result>
  <duration>1314443</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/jenkins_home/workspace/SistemaVentas</workspace>
  <hudsonVersion>2.462.2</hudsonVersion>
  <scm class="hudson.plugins.git.GitChangeLogParser" plugin="git@5.5.0">
    <authorOrCommitter>false</authorOrCommitter>
    <showEntireCommitSummaryInChanges>true</showEntireCommitSummaryInChanges>
  </scm>
  <culprits class="java.util.Collections$UnmodifiableSet">
    <c class="sorted-set">
      <string>mark.pino</string>
    </c>
  </culprits>
</build>